const GRAMMAR_CONSTANT = {
    GET_GRAMMAR: 'GET_GRAMMAR',
    GET_GRAMMAR_BY_ID: 'GET_GRAMMAR_BY_ID',
    GET_ALL_GRAMMAR: "GET_ALL_GRAMMAR",
    GET_GRAMMAR_BY_LEVEL: "GET_GRAMMAR_BY_LEVEL",
    GET_GRAMMAR_LEVELS: "GET_GRAMMAR_LEVELS",
    CREATE_GRAMMAR: "CREATE_GRAMMAR",
    EDIT_GRAMMAR: "EDIT_GRAMMAR",
    DELETE_GRAMMAR: "DELETE_GRAMMAR",
    SET_GRAMMAR_LOADING: "SET_GRAMMAR_LOADING",
    SET_GRAMMAR_ERROR: "SET_GRAMMAR_ERROR",

  }
  
  export default GRAMMAR_CONSTANT;
  