const LISTEN_CONSTANT = {
    GET_LISTEN: 'GET_LISTEN',
    GET_ALL_LISTEN: "GET_ALL_LSITEN",
    SET_LISTEN_LOADING: "SET_LISTEN_LOADING",
    SET_LISTEN_ERROR: "SET_LISTEN_ERROR",

  }
  
  export default LISTEN_CONSTANT;
  