const LISTEN_CONSTANT = {
    GET_LISTEN_BY_ID_REQUEST: 'GET_LISTEN_BY_ID_REQUEST',
    GET_LISTEN_BY_ID_SUCCESS: 'GET_LISTEN_BY_ID_SUCCESS',
    GET_LISTEN_BY_ID_FAILURE: 'GET_LISTEN_BY_ID_FAILURE',
  }
  
  export default LISTEN_CONSTANT;