const LISTEN_CONSTANT = {
    GET_LISTENING: 'GET_LISTENING',
    GET_LISTENING_QUIZ: 'GET_LISTENING_QUIZ',
    GET_LISTEN_BY_ID: 'GET_LISTEN_BY_ID',
    GET_ALL_LISTEN: "GET_ALL_LISTEN",
    GET_LISTEN_BY_TOPIC: "GET_LISTEN_BY_TOPIC",
    GET_LISTEN_TOPICS: "GET_LISTEN_TOPICS",
    CREATE_LISTEN: "CREATE_LISTEN",
    EDIT_LISTEN: "EDIT_LISTEN",
    DELETE_LISTEN: "DELETE_LISTEN",
    SEARCH_LISTEN: "SEARCH_LISTEN",
    SET_LISTEN_LOADING: "SET_LISTEN_LOADING",
    SET_LISTEN_ERROR: "SET_LISTEN_ERROR",

  }
  
  export default LISTEN_CONSTANT;
  