const QUESTION_CONSTANT = {
    GET_QUESTION: 'GET_QUESTION',
    GET_QUESTION_BY_QUIZ: 'GET_QUESTION_BY_QUIZ',
    CREATE_QUESTION: "CREATE_QUESTION",
    EDIT_QUESTION: "EDIT_QUESTION",
    DELETE_QUESTION_BY_QUIZ: "DELETE_QUESTION_BY_QUIZ",
    DELETE_QUESTION: "DELETE_QUESTION",
    SET_QUESTION_LOADING: "SET_QUESTION_LOADING",
    SET_QUESTION_ERROR: "SET_QUESTION_ERROR",

  }
  
  export default QUESTION_CONSTANT;
  