const QUIZ_CONSTANT = {
    GET_QUIZ_BY_LISTEN: 'GET_QUIZ_BY_LISTEN',
    GET_QUIZ_BY_ID: 'GET_QUIZ_BY_ID',
    SET_QUIZ_LOADING: "SET_QUIZ_LOADING",
    SET_QUIZ_ERROR: "SET_QUIZ_ERROR",

  }
  
  export default QUIZ_CONSTANT;
  