const QUIZ_CONSTANT = {
    GET_QUIZ: 'GET_QUIZ',
    GET_QUIZ_BY_LISTEN: 'GET_QUIZ_BY_LISTEN',
    GET_ALL_QUIZ: "GET_ALL_QUIZ",
    CREATE_QUIZ: "CREATE_QUIZ",
    DELETE_QUIZ_BY_LISTEN: "DELETE_QUIZ_BY_LISTEN",
    DELETE_QUIZ: "DELETE_QUIZ",
    SET_QUIZ_LOADING: "SET_QUIZ_LOADING",
    SET_QUIZ_ERROR: "SET_QUIZ_ERROR",

  }
  
  export default QUIZ_CONSTANT;
  