const WORD_CONSTANT = {
    GET_WORD: 'GET_WORD',
    GET_ALL_WORD: "GET_ALL_WORD",
    GET_WORD_BY_TOPIC: "GET_WORD_BY_TOPIC",
    GET_WORD_TOPICS: "GET_WORD_TOPICS",
    CREATE_WORD: "CREATE_WORD",
    EDIT_WORD: "EDIT_WORD",
    DELETE_WORD: "DELETE_WORD",
    SEARCH_WORD: "SEARCH_WORD",
    GET_WORDPACK: "GET_WORDPACK",
    EXIST_WORD: "EXIST_WORD",
    SET_WORD_LOADING: "SET_LISTEN_LOADING",
    SET_WORD_ERROR: "SET_WORD_ERROR",
  }
  
  export default WORD_CONSTANT;
  